### ISSUE TITLE
Command failing when setting stdout and stderr

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/datatypes#73]
This was roughly my command:

```python
Command(["echo", "foo bar"], stdout=sys.stdout, stderr=sys.stdout)
```

And this was the error:

```
Traceback (most recent call last):
  File ".../datatypes/command.py", line 82, in __iter__
    for line in iter(output.readline, b""):
AttributeError: 'NoneType' object has no attribute 'readline'

During handling of the above exception, another exception occurred:

  ...
  File ".../datatypes/command.py", line 88, in __iter__
    output.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by Jaymon** [comment]
This works for passthrough using `subprocess`:

```python
subprocess.check_call(["echo", "foo bar"], shell=False)
```
